### ISSUE TITLE
Add data to timestamps

### ISSUE THREAD

**Issue by Vafilor** [Vafilor/TimeTracker#17]
Idea here is to be able to keep track of different features over time, like heartrate. 

Some data might need multiple fields though, especially if we do reports or charts on it.

Current idea is adding a JSON column, with key/value pairs.
If we do that, need a nice way to display it in the ui.

It would actually be easiest to handle with API, because then you can pass in values right there.

For a CLI application, something like

/timestamp --heartrate=80

**Comment by aleksandrmelnikov** [comment]
Not certain what you mean by heart rate?

**Comment by Vafilor** [comment]
I'm thinking something like 

Timestamp: 12:00 PM 5/13/2021
 * Heart Rate: 80

Timestamp: 12:30 PM 5/13/2021
 * Heart Rate: 83

Right now Timestamps only have tags and a datetime

**Comment by aleksandrmelnikov** [comment]
Hmm, I think json makes sense.
Or some other flexible column format.

**Comment by Vafilor** [comment]
This has been added.
