### ISSUE TITLE
Look into alternate database structure for tag associations

### ISSUE THREAD

**Issue by Vafilor** [Vafilor/TimeTracker#23]
Right now a separate table is created for association.
So for Time Entries, we have
TimeEntryTag

and for Timestamps we have 
TimestampTag

This is an okay way to do it, but it seems a little redundant to have a separate table per entity.

Ideally we add a column identifying the resource like 'timestamp' and 'time-entry'.

This might be a bit difficult with Doctrine ORM.

Another approach is to have all of the related entities on one table, and have the others have a null value.

Something like
EntityTags
 * tag_id
 * timestamp_id: int | null
 * time_entry_id: int | null

---
design doc

* Know who created a tag
* Tags have a color
* Tags have an icon/image
* Have tag access control
  * A team can see all team tags
  * Andrey's private tags can not be seen by team
  * Admin can see all tags
* Assign multiple tags to an entity
* List all tags
* List number of uses of a tag, e.g. work has 50 entities using it.
* Find entities by having
  * no tags
  * tag A or B or C
  * tag A and B and C
* Avoid creating a Join table for tags and each entity
  * That is, if I have entities: tasks, users, there should not be a separate table for each linking to tags.

**Comment by aleksandrmelnikov** [comment]
I would suggest maybe trying a json column?
That way, you have one column.

But you store all the entities and their tags inside the json text.

**Comment by aleksandrmelnikov** [comment]
https://tapoueh.org/blog/2013/10/denormalizing-tags/
- This has an interesting display of querying multiple tags using a postgres feature

**Comment by aleksandrmelnikov** [comment]
One other thought I have is to automate it a bit from the code side.
- So you create an interface or maybe trait, and the doctrine entity could implement it.
- This could be picked up by the database migration code and generate it
- Plus, auto-complete should see that trait and be able to run the collection, query, and other CRUD operations.

**Comment by Vafilor** [comment]
An updated scheme has been implemented. Please see 
https://github.com/Vafilor/TimeTracker/blob/main/design_docs/tags.md

for more information. 

Going to close this out for now, but I'm always up for a discussion on a new way to do it.
