### ISSUE TITLE
Bug: You can create a task with the same exact name

### ISSUE THREAD

**Issue by aleksandrmelnikov** [Vafilor/TimeTracker#24]
It might not be a bug to allow this to happen, since the previous tasks can be completed.

However, I can't see the duplicate task in the index list.

**Comment by Vafilor** [comment]
@aleksandrmelnikov Can you check this again from main branch? I believe this has been fixed.

**Comment by Vafilor** [comment]
Going to close this as I believe it has been fixed. Please open a new issue if you find a bug.
