### ISSUE TITLE
Suggestion: Task search should be case insensitive

### ISSUE THREAD

**Issue by aleksandrmelnikov** [Vafilor/TimeTracker#27]
No auto complete
![image](https://user-images.githubusercontent.com/10407733/118597049-05af0900-b761-11eb-9254-88c4f579b2ed.png)

Auto complete
![image](https://user-images.githubusercontent.com/10407733/118597075-0c3d8080-b761-11eb-8035-3075644a12d8.png)

**Comment by Vafilor** [comment]
@aleksandrmelnikov This should be fixed on main branch, can you confirm?

For tracking: https://github.com/Vafilor/TimeTracker/issues/31

**Comment by Vafilor** [comment]
Going to mark this one as done. Please re-open the issue if you notice any issues.
