### ISSUE TITLE
Bug: Duration is incorrect for 10 AM start, 12 PM finish

### ISSUE THREAD

**Issue by aleksandrmelnikov** [Vafilor/TimeTracker#36]
See picture:
![image](https://user-images.githubusercontent.com/10407733/119041336-5b570180-b96b-11eb-9d57-52dfea0c81af.png)

**Comment by Vafilor** [comment]
This should fix it: https://github.com/Vafilor/TimeTracker/commit/81c7ffdeb5b121b3752a894c96fce7f0605fb9b9

Please re-open issue if it is not resolved.
