### ISSUE TITLE
Import/Export data command

### ISSUE THREAD

**Issue by Vafilor** [Vafilor/TimeTracker#50]
As a user of the application, I want to be able to export my local data and import it into a web server in the cloud so that I still have my data to work with. 

Similarly, I want to export my web server data and import it locally so I can continue on.

This would also be very handy for testing different databases so I don't start with empty data all of the time.

**Comment by aleksandrmelnikov** [comment]
Is this more than a database dump?

**Comment by Vafilor** [comment]
Kinda. It's in a json format, so you could use it for your own purposes if you like. But it's also not tied to a specific database, so you could use postgres locally and export it, and import to a mysql database.
