### ISSUE TITLE
JSON responses do not have "optional" data

### ISSUE THREAD

**Issue by Vafilor** [Vafilor/TimeTracker#54]
Right now the JSON responses return null for fields instead of not having the fields at all.

Need to check if it is easy enough to do with the symfony serializer, and if there would be any other potential issues. 

If not, remove the fields instead of having nulls.

**Comment by Vafilor** [comment]
One of the issues is, if you don't initialize a nullable value in a class, the serializer won't serialize it at all, even if you set it later.
I think this is due to the json_encode method.

But, if you do initialize it, either in the constructor or at the properly declaration, it works fine.

In that case, you can use:

```            
$serializer->serialize($data, 'json', [
                AbstractObjectNormalizer::SKIP_NULL_VALUES => true
            ]);
```

So I'll work on updating this.

**Comment by aleksandrmelnikov** [comment]
Sounds like you have to be careful in designing default initialized values?

On Thu, Jun 10, 2021, at 8:55 PM, Andrey Melnikov wrote:
> 


> One of the issues is, if you don't initialize a nullable value in a class, the serializer won't serialize it at all, even if you set it later.
> I think this is due to the json_encode method.

> But, if you do initialize it, either in the constructor or at the properly declaration, it works fine.

> In that case, you can use:

> `$serializer->serialize($data, 'json', [
                AbstractObjectNormalizer::SKIP_NULL_VALUES => true
            ]);
`

**Comment by Vafilor** [comment]
@aleksandrmelnikov Yeah, a little bit. The error messages are pretty nice though.

Really, you just have to initialize them in the constructor, and it all seems to be fine.

e.g. 

```php
class Test {
  public ?string $rand;
  
  public function __construct()
  {
      $this->rand = null;
      if (random_int(0, 10) > 5) {
         $this->rand = 'wow';
      }
  }
}
```
